const NUMBER = 'NUMBER';
const LINEAR_SCALE = 'LINEAR_SCALE';
const IMG_LINEAR_SCALE = 'IMG_LINEAR_SCALE';
const DATE = 'DATE';
const TIME = 'TIME';
const DATE_TIME = 'DATE_TIME';
const CHECKBOX = 'CHECKBOX';
const MULT_CHOICE = 'MULT_CHOICE';
const SHORT_ANSWER = 'SHORT_ANSWER';
const LONG_ANSWER = 'LONG_ANSWER';
const CHECKBOX_GRID = 'CHECKBOX_GRID';
const MULT_CHOICE_GRID = 'MULT_CHOICE_GRID';

const questionTypes = [
  NUMBER,
  LINEAR_SCALE,
  IMG_LINEAR_SCALE,
  DATE,
  TIME,
  DATE_TIME,
  CHECKBOX,
  MULT_CHOICE,
  SHORT_ANSWER,
  LONG_ANSWER,
  CHECKBOX_GRID,
  MULT_CHOICE_GRID,
];

module.exports = {
  NUMBER,
  LINEAR_SCALE,
  IMG_LINEAR_SCALE,
  DATE,
  TIME,
  DATE_TIME,
  CHECKBOX,
  MULT_CHOICE,
  SHORT_ANSWER,
  LONG_ANSWER,
  CHECKBOX_GRID,
  MULT_CHOICE_GRID,
  questionTypes,
};
